
---
# This playbook deploys the entire setup to the Cloud9 development environment.
- hosts: all
  vars:
    # ansible_python_interpreter: /usr/bin/python2.7
  roles:
   - development
  vars_files:
    - ~/environment/.secrets/.ansible_secrets.yml
